version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
        image: us-central1-docker.pkg.dev/backdoorctf-2023/bckdrchallenges/toomanyadmins:v1
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: qwertyuiopplaqswdefgxcvbn
            MYSQL_DATABASE: qwertyuiopplaqswdefgxcvbnzxcbak
        volumes:
            - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - "9906:3306"
    